### ISSUE TITLE
Two functions 'sequence_to_tree' and 'scenario_to_tree' seems inconsistent with comments

### ISSUE THREAD

**Issue by AutoTemp** [facebookresearch/TreeNLG#1]
sequence_to_tree's comments says:
[__DG_INFORM_2__ supposed to __ARG:CONDITION_NOT__ ]
    =>
    NLGNode("root", children={
        NLGNode("[__DG_INFORM_2__", children={NLGNode("__ARG:CONDITION_NOT__")})
    })

but actual result is:
NLGNode("root", children={
        NLGNode("[__DG_INFORM_2__")
    })

scenario_to_tree's comment says:
[__DG_INFORM__: [__ARG_TASK__: get_forecast , __ARG_TEMP_HIGH__: 33 ] ]
    =>
    NLGNode("root", children={
        NLGNode("[__1_DG_INFORM__", children={
            NLGNode("__ARG_TEMP_HIGH__", children={
                NLGNode("33")
            }),
            NLGNode("__ARG_TASK__", children={
                NLGNode("get_forecast")
            })
        })
    })

but actual result is:
NLGNode("root", children={
        NLGNode("[__1_DG_INFORM__", children={
            NLGNode("__ARG_TASK__", children={
                NLGNode("get_forecast , __ARG_TEMP_HIGH__: 33")
            })
        })
    })

Thanks!

**Comment by jinfengr** [comment]
Hi @sx349995780 Thanks for your interests.

This is because of our out-dated comments, and I have fixed these inconsistencies in the comments and updates in commit `b97ecba29753cd30435dd8ea6adc768eb086b659`. 

To be more clear:

1) Given input as "[__DG_INFORM__ supposed to [__ARG_CONDITION_NOT__ not rain ] ]", the output of `sequence_to_tree` is: 
`NLGNode("root", children={
NLGNode("[__DG_INFORM__", children={NLGNode("__ARG_CONDITION_NOT__")})
})`


2) Given input as "[__DG_INFORM__: [__ARG_TASK__: get_forecast ] [__ARG_TEMP_HIGH__: 33 ] ]", the output of `scenario_to_tree` is:
`NLGNode("root", children={
NLGNode("[__DG_INFORM__", children={
NLGNode("[__ARG_TEMP_HIGH__", children={
NLGNode("33")
}),
NLGNode("[__ARG_TASK__", children={
NLGNode("get_forecast")
})
})
})`

**Comment by jinfengr** [comment]
Also I have run offline tests and verified the correctness of tree accuracy calculation. Please feel free to use it.
