### ISSUE TITLE
Where to get complete information related to data stracture/formatting used here

### ISSUE THREAD

**Issue by JKP0** [facebookresearch/TreeNLG#10]
Hey, 
Please can you refer me some link or direction where I can get, the complete information to understand the data stracture/formatting used with [data](https://github.com/facebookresearch/TreeNLG/tree/master/data) given in the repo. 

### **In other words, how to explain each word/term/feature of a single sample of the data-set used here?**

**Comment by znculee** [comment]
Not sure if I understand your question very well. To understand the data, you may refer to the paper supported by this repo.
[Constrained Decoding for Neural NLG from Compositional Representations in Task-Oriented Dialogue](https://www.aclweb.org/anthology/P19-1080/)

**Comment by JKP0** [comment]
Hey @znculee  thanks for your response, we have gone through this paper.

The paper doesn't describes about need and meaning of specific Dialogs and Discourses used in the data set.

The paper is also silent on Dialog-Discourse relations and Inter-Discourse relations (primarily considered relations). Paper doesn't explains how and why a Dialog is connected to a Discourse, and based on which rule Inter-Discourse connection/relation and Dialog-Discourse connection/relation is defined.

Paper is also silent on how one can decide about Dialog and Discourse tag for the given sample in semantic representation or raw structured format or simple sequence of text.

**Comment by jinfengr** [comment]
Hi @JKP0 , the design of dialog acts and discourse relations are done by our linguists, where dialog acts are meant to denote the minimum semantic unit (or intent) of a clause or sub-clause, and discourse relations are descriptions of how two or multiple segments of clauses/information are logically connected. Common discourse relations are Join, Contrast and Justify, and you can find how they are used from concrete examples in our dataset. By default, a discourse relation can enclose any dialog act as it children (though realistically a discourse relation may only enclose certain DAs).

For the weather dataset, since we generate the scenarios using rules before we send them out for annotation. The discourse tags are predefined when creating the scenarios. For example, Contrast is mostly used for a weather query about a range of dates, and the conditions in the range are different with each other; Justify is mostly used when we are recommending certain actions (e.g., bring an umbrella) and we explain the reason to our users (e.g., it will rain). 

For the E2E dataset, you can check out how we add discourse tags using some simple rules in Section 3.2.

**Comment by JKP0** [comment]
@jinfengr Thanks a lot, This clarifies till a good extent. Thank you!

It requested, if you know any documented  complete information sources to clarify it more/completely, Please post information in the comment. Thanks in advance!
